language: ruby
cache: bundler
rvm:
  - ruby-head
  - 2.7.3
  - 2.6.6
  - 2.5.8
  - truffleruby-head
gemfile:
  - gemfiles/rails_6.1.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_5.2.gemfile
matrix:
  exclude:
    - rvm: ruby-head
      gemfile: gemfiles/rails_5.2.gemfile
  allow_failures:
    - rvm: ruby-head
    - rvm: truffleruby-head
